### ISSUE TITLE
범위 예외처리 오류(by. jjo)

### ISSUE THREAD

**Issue by AimingBro** [Moongss/42Seoul_factorization#1]
안녕하세요. 정말 코드를 가독성있고 깔끔하게 잘 짜셨는데, 예외처리에서 약간의 실수가 있으셨던거 같습니다.
범위내의 값을 입력했는데도, 예외처리가 메세지가 출력 되었습니다..ㅜㅜ
![image](https://user-images.githubusercontent.com/53181778/78322961-512d4480-75ab-11ea-9478-dd030aebd064.png)

**Comment by Moongss** [comment]
10자리일 때 UINT_MAX 초과 범위의 수를 처리하는 로직이 잘못됐네요. 이슈 감사합니다!
