### ISSUE TITLE
ERROR처리가 인상깊었습니다! 하지만 int범위 밖 unsigned int 범위 안 소수에 대한 에러가 있는 것 같습니다.

### ISSUE THREAD

**Issue by QKRM** [Moongss/42Seoul_factorization#2]
![image](https://user-images.githubusercontent.com/48343739/78332230-8e510100-75c2-11ea-8573-21645768c0e5.png)

보시면 UINT_MAX는 정상적으로 처리하지만, 3000066863은 소수임에도 에러 메시지가 나오네요!
별개로 0~9가 아닌 문자가 입력되었을때 어떤 문자가 에러를 발생시켰는지 출력해주시는건 매우 친절한 오류처리 같습니다!

**Comment by Moongss** [comment]
앞서 jjo님이 달아주신 이슈를 보고 바로 알아챘습니다 ㅠㅠ 10자리의 수가 들어왔을 때의 예외를 잘못 처리해 발생한 에러네요. 이슈 감사합니다!
