### ISSUE TITLE
널값처리, 4294967294에서 오류발생.

### ISSUE THREAD

**Issue by witcher42** [Moongss/42Seoul_factorization#3]
전반적으로 잘 작동합니다. 다만,
널값을 수로 인식한 것과 4294967294에서 2가 소인수로 출력되지 않은 점이 아쉽습니다.
매크로를 사용하여 코드를 깔끔하게 만드셔서 제가 이해하는데 많은 도움이 되었습니다~

![스크린샷(180)](https://user-images.githubusercontent.com/59954400/78451108-7363b700-76be-11ea-98fd-1ee9555662e5.png)

**Comment by Moongss** [comment]
늦었지만 꼼꼼한 리뷰 감사드립니다~~
