### ISSUE TITLE
코드리뷰(eunhkim)

### ISSUE THREAD

**Issue by eunhyulkim** [Moongss/42Seoul_factorization#4]
안녕하세요. 수고 많으셨습니다! 직접 코드를 클론해서 테스트해보았고, 아래와 같이 리뷰 남깁니다.

## 에러
1. 일부 케이스의 경우 출력에 문제가 있습니다.
```
./factorization 4294967293
9241464773
```
```
./factorization 4294967294
22147483647
```
확인결과 65535가 소수를 판별하기 위해 기준으로 잡힌 값인데, 65535보다 크면서 65535보다 큰 소수를 소인수로 가지는 수가 인자로 입력될 경우 65535보다 작은 소인수들만 출력하고 반복문을 탈출하게 됩니다. 
```
while (divisor <= 65535 && number > 1)
```
아래 라인에서 spaceCheck가 TRUE일 경우 스페이스를 출력하고 숫자를 출력하도록 코드를 추가하면 해결될 것 같습니다.
```
if (number > 1)
	ft_putnbr(number);
```

## 개선사항
1. ft_atoi의 리턴값이 int로 되어 있습니다. unsigned int로 수정되어야 할 것으로 보입니다.

2. ft_print_error에서 에러 출력시 write로 에러 메시지를 곧장 출력하기 때문에, 세 번째 인자로 에러 메시지의 길이가 오고 있는데 유지보수에 있어 불편하게 보입니다. ft_strlen이나 ft_putstr을 이용하는 게 나아보입니다.

## 배운 점 & 좋았던 점
코드가 무척 간결하고 가독성이 뛰어났습니다. 구조 및 함수 설계, 정렬, 함수 주석, 변수명까지 깔끔 그 자체인 것 같아요. err_msg에 info를 활용하신 것도 그렇고, 특히 ERROR 코드를 '2 << 1'과 같이 비트를 이용해서 처리한 테크닉과 함수마다 달아놓으신 주석 형식을 보면서 학습할 점이 많았습니다.  

다시 한 번 정말 수고 많으셨습니다!

**Comment by Moongss** [comment]
에러사항에 대한 해결 코드, 개선사항까지 꼼꼼히 적어주신걸 보고 다시 제 코드를 리뷰할 수 있었습니다!
피드백 감사드립니다~~
